Header
LIGHT131313/watchspot pull request #10
Opened 2023-04-23 16:56 UTC by Sergeyy321

2023-04-23 17:40 UTC, wxoox2000 approved these changes
Didn't find any issues, good work!

2023-04-23 19:03 UTC, LIGHT131313 commented on src/css/mobmenu — копия.css
delete file

2023-04-23 19:05 UTC, LIGHT131313 commented on src/partials/header.html
> +  <a href="./index.html" class="logo-svg"><load src="partials/logo.html" class=""/></a>
thewatchspot - the text needs to be inserted into the logo link

2023-04-23 19:06 UTC, LIGHT131313 commented on src/css/header.css
> +.text-header{font-family: Epilogue;font-style: normal;
delete: Epilogue;font-style: normal;
    font-weight: 400;

2023-04-23 19:09 UTC, LIGHT131313 commented on src/css/header.css
make the code readable (indents and line breaks)

2023-04-23 19:11 UTC, LIGHT131313 commented on src/css/header.css
center menus horizontally

2023-04-23 20:35 UTC, Fetivol commented
1. Текст в кнопці нахилений, а повинен стояти рівно
2. Чомусь стилі не затягнулись для Лінків/якорів та текст не виглядає так само, як на макеті

2023-04-24 17:02 UTC, ppavel123 requested changes

2023-04-24 17:02 UTC, ppavel123 commented on src/partials/header.html
> +  <a href="./index.html" class="logo-svg" ><load src="partials/logo.html" />thewatchspot</a>
замінити тег load

2023-04-24 17:06 UTC, ppavel123 commented on src/partials/header.html
> +  <a href="./index.html" class="logo-svg" ><load src="partials/logo.html" />thewatchspot</a>
задати колір назві компанії

2023-04-25 14:30 UTC, closed without merging