gif-problem
LIGHT131313/watchspot pull request #13
Opened 2023-04-24 13:29 UTC by lllapinski

2023-04-24 13:49 UTC, ppavel123 commented on src/css/aboutus.css
> +margin-top: 40px;
Потрібно замінити верхній маржн заголовку, на падінг заданий секції

2023-04-24 13:53 UTC, ppavel123 commented on src/css/aboutus.css
> +margin-top: 64px;
Замінити на падінг для контейнера

2023-04-24 14:01 UTC, ppavel123 requested changes
Також Гіф на ПК версії має бути на всю ширину

2023-04-24 17:24 UTC, LIGHT131313 commented on src/partials/aboutus.html
> +</header> -->
delete

2023-04-24 17:28 UTC, LIGHT131313 commented on src/partials/aboutus.html
> +    <ul class="about-us-list">
it's a div

2023-04-24 17:28 UTC, LIGHT131313 commented on src/partials/aboutus.html
> +        <li class="about-us-list-item">
it's a div

2023-04-24 17:30 UTC, LIGHT131313 commented on src/partials/aboutus.html
in your section should not have "ul" and "li"

2023-04-24 17:32 UTC, lllapinski commented on src/partials/aboutus.html
чим треба їх замінити?

2023-04-24 18:28 UTC, Fetivol commented on src/partials/aboutus.html
Тут буде краще задати два різні елементи <p>, тоді не потрібно буде знімати стилі з Юл та Іл

2023-04-24 18:31 UTC, lllapinski commented on src/partials/aboutus.html
я не до кінця розумію які елементи(

2023-04-24 18:49 UTC, wxoox2000 commented on src/partials/aboutus.html
Вам тут не потрібні ul та li, у вас просто заголовок h2 та 2 р. І тоді або 2 р загортаєте в дів з флексом, як ви і робили, або навіть можна на таблет/десктоп версіях дати їм разом із заголовком display: inline-block, і тоді їм можна задавати ширину як по макету, а вони будуть вставати в ряд

2023-04-24 18:52 UTC, wxoox2000 commented on src/partials/aboutus.html
> +      <h1 class="about-us-title" id="aboutus">About us</h1>
Має бути h2, бо h1 - це головний заголовок сайту (у секції Hero), а далі заголовки секцій.

2023-04-24 19:36 UTC, lllapinski commented on src/partials/aboutus.html
дякую, виправила!)

2023-04-24 19:40 UTC, Fetivol commented on src/partials/aboutus.html
Для гіфки поки що бачу тільки одне розвʼязання - це задати висоту для кожного медіа запиту

2023-04-24 20:06 UTC, lllapinski commented
так а чому на всю ширину? в нього ж фіксована ширина я, я вказала так як і
на макеті

пн, 24 апр. 2023 г. в 16:01, ppavel123 ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Також Гіф на ПК версії має бути на всю ширину
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LIGHT131313/watchspot/pull/13#pullrequestreview-1398074786>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6ABD75GKB2OVQJBEVFXXJTXC2BURANCNFSM6AAAAAAXJS2LTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-25 03:56 UTC, LIGHT131313 commented on src/partials/aboutus.html
> +<div class="about-us  container">
change this div to section

2023-04-25 03:57 UTC, LIGHT131313 commented on src/partials/aboutus.html
> +<img class="about-us-gif" src="../img/about-us/watchspot.gif" alt="Our watches gif">
one dot src="../img/about-us/watchspot.gif"

2023-04-25 04:02 UTC, LIGHT131313 commented on src/css/aboutus.css
> +    padding-top: 40px;
+padding-bottom: 40px

2023-04-25 04:03 UTC, LIGHT131313 commented on src/css/aboutus.css
> +        padding-top: 64px;
+padding-bottom: 64px

2023-04-25 04:03 UTC, LIGHT131313 commented on src/css/aboutus.css
> +    padding-top: 80px;
+padding-bottom: 80px

2023-04-25 07:41 UTC, lllapinski commented on src/partials/aboutus.html
а навіщо задавати висоту гіфці на медіазапитах? в дефолтних стилях для img задано height:auto

2023-04-25 11:49 UTC, merged