Update modal.html
LIGHT131313/watchspot pull request #2
Opened 2023-04-21 19:03 UTC by OlenaKuchma

Наразі пробний html - не для перевірки. пробую зрозуміти як це працює.

2023-04-21 19:15 UTC, ppavel123 reviewed
тест

2023-04-21 19:15 UTC, ppavel123 commented on src/partials/modal.html
> +            href="./images/icon/symbol-defs.svg#icon-close-black-18dp"
тест

2023-04-21 19:29 UTC, LIGHT131313 requested changes
test

2023-04-21 19:50 UTC, OlenaKuchma commented
так. написала пробний код для модалки. 
Відразу питання картинка з описом - як в розділі Каталог. Мені її окремо верстати чи можна взяти код в того хто пише каталог? Я так розумію, що модалка саме на каталогу відкривається. 
Як мені прописати скрипт на каталог потім? Чи можна брати файл зі скриптом як на навчанні (простішим, а не тим що в Репети?)
Текст під кнопкою - це просто параграф? чи кнопка це чекбокс?
Наразі все.

2023-04-21 20:03 UTC, OlenaKuchma commented
Я вже оновила код, це вже не пробний, а початковий. Навіщо його закривати?

2023-04-21 20:07 UTC, OlenaKuchma commented on src/partials/modal.html
> +            href="./images/icon/symbol-defs.svg#icon-close-black-18dp"
Я вже оновила код під нашу модалку початково. Щось не зовсім розумію навіщо його закривати? Я маю кілька питань на завтра щоб зрозуміти як працювати далі.

2023-04-22 15:15 UTC, OlenaKuchma commented
Скидаю пробний варіант для Ваших коментарів та правок. 
Кнопку закриття наразі зробила тимчасову - фон - поки не зрозуміло, що зі спрайтом.
Не зовсім зрозуміла ситуація з ціною - там прихований case - який не зявляється на жодному варіанті - можливо там автоматичне вираховування ціни має бути....

2023-04-22 16:49 UTC, Yuliia2391 commented
Це поки що все, що я побачила.

В css не потрібні задані властивості, чкі внесені класам до класу .backdrop. Вони всі є в файлі reset.css 

1. mobile CSS.modal {padding: 40px 20px;}
2. HTML .modal-text-wrap-text, можливо можна було зробити його <p> та стилізувати
3. mobile В макеті між <label> та <input> відстань 12px
4. tab Кнопка закриття модального вікна top, rigth 20px
5. В десктопній версії текст Privacy Policy в макеті стоїть не по всій ширині
6. СSS .backdrop в transition задано opacity, мені здається, що .backdrop потрібно також задати opacity

Script такий, як і в домашці був, але не розумію чи він вже повинен працювати, чи він буде працювати коли будуть зібрані всі секції.

2023-04-22 17:56 UTC, OlenaKuchma commented
1. в ресет вони для контейнера, якого в модалці немає.
2. я зробила так як було написано для каталогу....
3. за це дякую, в мене було тільки 4 чомусь....
4. ні.. 26...як, а в десктопній, якраз 20 - дякую....
5. та... знаю, але не знаю як розділити, крім як </br> - може хтось підскаже...
6. не зовсім розумію - він стає прозорий коли закривається модалка...
7. скрипт я наразі не додавала взагалі ніякий -

2023-04-22 20:50 UTC, Fetivol approved these changes
Я не знайшов, що додати від інших, тому кидаю апрув

2023-04-23 06:30 UTC, LIGHT131313 commented on src/css/modal.css
> +}
Все це є в reset.css, можете видаляти, клас link також не потрібен це a в reset.css

2023-04-23 06:33 UTC, LIGHT131313 commented on src/css/modal.css
> +    visibility 250ms cubic-bezier(0.4, 0, 0.2, 1);
ось тут можете просто вказувати transition: opacity var(--transition),
    visibility  var(--transition);

2023-04-23 06:35 UTC, LIGHT131313 commented on src/css/modal.css
> +  background-color: #ffffff;
аналогічно і ось тут background-color: var(--color-white); і далі де будете використовувати змінні. Один раз вкажете і потім Еммет буде допомагати вам його обирати

2023-04-23 06:39 UTC, LIGHT131313 commented on src/css/modal.css
> +  color: black;
колір повинен бути #141414, тобто color: var(--color-black);

2023-04-23 06:40 UTC, LIGHT131313 commented on src/css/modal.css
> +  color: black;
колір повинен бути #141414, тобто color: var(--color-black);

2023-04-23 06:43 UTC, LIGHT131313 commented on src/css/modal.css
> +.modal-sent-btn {
hover, focus зробіть як у Buy now

2023-04-23 06:53 UTC, LIGHT131313 commented on src/css/modal.css
> +.modal-sent-btn-text {
для лінка в цьому тексті зробіть hover, focus   opacity 0.7 та підкреслення

2023-04-24 10:51 UTC, merged